name: Deploy com Migrations

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar Supabase CLI
        run: npm install -g supabase

      - name: Linkar projeto
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Rodar migrations
        run: supabase db push

  deploy:
    needs: migrate
    runs-on: ubuntu-latest

    steps:
      - run: echo "Aqui você pode chamar deploy da Vercel"